import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {Miniflare} from 'miniflare';
import {normalizeReelUrl,isInstagramCdn} from '../src/url.js';
import {CobaltDownloader,PublicInstagramDownloader,fetchVideo} from '../src/downloader.js';
import {Reposter} from '../src/jobs.js';
import {MetaClient,CAPTION} from '../src/meta.js';
import {getAccessToken} from '../src/tokens.js';
import {AppError} from '../src/errors.js';
import relay from '../transport/worker.js';
let mf,db,bucket,sequence=0;
before(async()=>{mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2025-10-01',d1Databases:{DB:'jobs'},r2Buckets:['BUCKET']});db=await mf.getD1Database('DB');bucket=await mf.getR2Bucket('BUCKET');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').filter(s=>s.trim()))await db.prepare(sql).run();});
after(async()=>{await mf?.dispose();});
function fixture({stageFailure,deleteFailure=false,processing='FINISHED',publishNetwork=false}={}){
  let now=Date.now()+sequence*10000000;const code='TestCase'+(++sequence);const counts={download:0,create:0,publish:0,delete:0};
  // Miniflare's Node RPC drops stream length metadata. Buffer ONLY the 12-byte test fixture;
  // deployed Workers use the native upstream response body with its known Content-Length.
  const env={DB:db,BUCKET:{put:async(k,value,options)=>{if(stageFailure==='storage')throw new AppError('Storage unavailable','preparing');const fixtureBytes=await new Response(value).arrayBuffer();assert.equal(fixtureBytes.byteLength,12);return bucket.put(k,fixtureBytes,options);},head:(...x)=>bucket.head(...x),get:(...x)=>bucket.get(...x),list:(...x)=>bucket.list(...x),delete:async(...x)=>{counts.delete++;if(deleteFailure)throw Error('no storage');return bucket.delete(...x);}},TRANSPORT_ORIGIN:'https://transport.example',INSTAGRAM_APP_SECRET:'test-only-secret',INSTAGRAM_APP_ID:'11111',INSTAGRAM_USER_ID:'22222',INSTAGRAM_ACCESS_TOKEN:'test-only-token'};
  const meta={create:async()=>{counts.create++;if(stageFailure==='create')throw new AppError('Container rejected','sending');return '12345678';},status:async()=>({code:stageFailure==='processing'?'ERROR':processing,message:'Processing rejected'}),publish:async()=>{counts.publish++;if(stageFailure==='publish'||publishNetwork)throw new AppError('Publish response interrupted','publishing');return '98765432';}};
  const downloader={download:async()=>{counts.download++;if(stageFailure==='download')throw new AppError('Public video unavailable','downloading');return{mediaUrl:'https://scontent.cdninstagram.com/source.mp4',mimeType:'video/mp4'};}};
  const fetcher=async()=>new Response(new Uint8Array([0,0,0,24,102,116,121,112,109,112,52,50]),{headers:{'Content-Type':'video/mp4','Content-Length':'12'}});
  const app=new Reposter(env,{downloader,meta,fetcher,now:()=>now});return{app,env,counts,code,id:crypto.randomUUID(),tick:()=>{now+=61000;},age:()=>{now+=7*3600000;}};
}
async function ready(f){await f.app.create(f.id,`https://instagram.com/reel/${f.code}/`);await f.app.advance(f.id);await f.app.advance(f.id);f.tick();}
test('normalizes valid Reel, plural Reel, video post and query strings',()=>{for(const p of['reel','reels','p'])assert.deepEqual(normalizeReelUrl(`https://instagram.com/${p}/Db8yWXrswOT/?igsh=hello#fragment`),{url:'https://www.instagram.com/reel/Db8yWXrswOT/',shortcode:'Db8yWXrswOT'});});
test('custom caption is persisted once and passed unchanged to Meta',async()=>{const f=fixture();let caption;f.app.meta.create=async(_url,_ai,value)=>{caption=value;return '12345678';};await f.app.create(f.id,`https://instagram.com/reel/${f.code}/`,'My custom caption 🎬');await f.app.create(f.id,`https://instagram.com/reel/${f.code}/`,'different retry caption');await f.app.advance(f.id);await f.app.advance(f.id);assert.equal(caption,'My custom caption 🎬');assert.equal((await f.app.store.get(f.id)).caption,caption);await assert.rejects(()=>f.app.create(crypto.randomUUID(),`https://instagram.com/reel/${f.code}/`,'x'.repeat(2201)));});
test('rejects malformed URLs, unsupported Instagram paths and fake hosts',()=>{for(const u of['bad','http://instagram.com/reel/Abc123/','https://instagram.com.evil.test/reel/Abc123/','https://evilinstagram.com/reel/Abc123/','https://instagram.com@evil.test/reel/Abc123/','https://www.instagram.com:8443/reel/Abc123/','https://www.instagram.com/explore/','https://www.instagram.com/reel/Abc123/extra','https://www.instagram.com/reel/%2e%2e/','https://www.instagram.com\\@evil.test/reel/Abc123/'])assert.throws(()=>normalizeReelUrl(u));});
test('CDN URL allowlist prevents SSRF',()=>{assert.equal(isInstagramCdn('https://scontent.cdninstagram.com/a.mp4'),true);for(const u of['https://cdninstagram.com.evil.test/a','https://127.0.0.1/a','http://scontent.cdninstagram.com/a','https://scontent.cdninstagram.com:8080/a','https://name:password@scontent.cdninstagram.com/a'])assert.equal(isInstagramCdn(u),false);});
test('Cobalt maintained API success and failure',async()=>{const a=new CobaltDownloader('https://cobalt.example/','secret',async(url,o)=>{assert.equal(JSON.parse(o.body).localProcessing,'disabled');assert.equal(o.headers.Authorization,'Api-Key secret');return Response.json({status:'redirect',url:'https://scontent.cdninstagram.com/a.mp4'});});assert.equal((await a.download('https://instagram.com/reel/Abc123/')).mimeType,'video/mp4');const b=new CobaltDownloader('https://cobalt.example/','',async()=>Response.json({status:'error',error:{code:'error.api.fetch.empty'}}));await assert.rejects(()=>b.download('https://instagram.com/reel/Abc123/'));});
test('anonymous embed downloader reads only the requested public single video',async()=>{const data={context:{shortcode:'Abc123'},gql_data:{shortcode_media:{is_video:true,video_url:'https://scontent.cdninstagram.com/a.mp4',owner:{is_private:false}}}};const html='"contextJSON":'+JSON.stringify(JSON.stringify(data));const d=new PublicInstagramDownloader(async u=>new Response(String(u).includes('/embed/')?html:'', {headers:{'content-type':'text/html'}}));assert.equal((await d.download('https://instagram.com/reel/Abc123/')).mimeType,'video/mp4');data.gql_data.shortcode_media.owner.is_private=true;const e=new PublicInstagramDownloader(async()=>new Response('"contextJSON":'+JSON.stringify(JSON.stringify(data))));await assert.rejects(()=>e.download('https://instagram.com/reel/Abc123/'));});
test('rejects redirects to internal or arbitrary media URLs',async()=>{await assert.rejects(()=>fetchVideo('https://scontent.cdninstagram.com/a.mp4',async()=>new Response(null,{status:302,headers:{location:'http://169.254.169.254/'}})));});
test('temporary storage and successful publish immediately remove R2 video',async()=>{const f=fixture();await ready(f);const j=await f.app.advance(f.id);assert.equal(j.status,'published');assert.equal(j.mediaId,'98765432');assert.equal(j.cleanupPending,false);assert.equal(await bucket.head(`temp-reels/${f.id}/source.mp4`),null);assert.equal(f.counts.publish,1);});
for(const stage of['download','storage','create','processing'])test(`${stage} failure is stage-specific and cleans media safely`,async()=>{const f=fixture({stageFailure:stage});await ready(f);const j=await f.app.advance(f.id);assert.equal(j.status,'failed');assert.ok(j.error);assert.equal(f.counts.publish,0);assert.equal(await bucket.head(`temp-reels/${f.id}/source.mp4`),null);});
test('media_publish failure / lost response never causes a second publish',async()=>{const f=fixture({publishNetwork:true});await ready(f);const j=await f.app.advance(f.id);assert.equal(j.status,'uncertain');assert.equal(j.retrySafe,false);f.tick();await f.app.advance(f.id);await assert.rejects(()=>f.app.retry(f.id));assert.equal(f.counts.publish,1);});
test('duplicate POST and different click IDs converge on the same durable job',async()=>{const f=fixture();const u=`https://instagram.com/reel/${f.code}/`;const jobs=await Promise.all(Array.from({length:8},()=>f.app.create(crypto.randomUUID(),u)));assert.equal(new Set(jobs.map(j=>j.id)).size,1);});
test('concurrent advance requests cannot double media_publish',async()=>{const f=fixture();await ready(f);await Promise.all(Array.from({length:12},()=>f.app.advance(f.id)));assert.equal(f.counts.publish,1);assert.equal((await f.app.store.get(f.id)).media_id,'98765432');});
test('retry after successful publish returns existing success without a new post',async()=>{const f=fixture();await ready(f);await f.app.advance(f.id);assert.equal((await f.app.retry(f.id)).status,'published');await f.app.advance(f.id);assert.equal(f.counts.publish,1);});
test('retry after download failure clears cleanup state so maintenance cannot delete the fresh video',async()=>{const f=fixture({stageFailure:'download'});await f.app.create(f.id,`https://instagram.com/reel/${f.code}/`);assert.equal((await f.app.advance(f.id)).status,'failed');assert.equal((await f.app.store.get(f.id)).cleanup_pending,0);f.app.downloader={download:async()=>({mediaUrl:'https://scontent.cdninstagram.com/source.mp4',mimeType:'video/mp4'})};await f.app.retry(f.id);assert.equal((await f.app.advance(f.id)).status,'sending');await f.app.maintenance();assert.ok(await bucket.head(`temp-reels/${f.id}/source.mp4`));assert.equal((await f.app.store.get(f.id)).status,'sending');await f.app.advance(f.id);f.tick();assert.equal((await f.app.advance(f.id)).status,'published');assert.equal(f.counts.publish,1);assert.equal(await bucket.head(`temp-reels/${f.id}/source.mp4`),null);});
test('crash after publish response but before saving media ID prevents any retransmission',async()=>{const f=fixture();await ready(f);const original=f.app.store.update.bind(f.app.store);let fail=true;f.app.store.update=async(id,patch,lease)=>{if(patch.media_id&&fail){fail=false;throw Error('DB interruption');}return original(id,patch,lease);};assert.equal((await f.app.advance(f.id)).status,'uncertain');f.tick();await f.app.advance(f.id);assert.equal(f.counts.publish,1);});
test('slow Meta processing retains temporary video and never publishes early',async()=>{const f=fixture({processing:'IN_PROGRESS'});await ready(f);f.age();const j=await f.app.advance(f.id);assert.equal(j.status,'processing');await f.app.maintenance();assert.ok(await bucket.head(`temp-reels/${f.id}/source.mp4`));assert.equal(f.counts.publish,0);});
test('failed cleanup keeps saved success and can retry cleanup without publishing again',async()=>{const f=fixture({deleteFailure:true});await ready(f);let j=await f.app.advance(f.id);assert.equal(j.status,'published');assert.equal(j.cleanupPending,true);f.env.BUCKET=bucket;await f.app.advance(f.id);j=await f.app.store.get(f.id);assert.equal(j.object_key,null);assert.equal(f.counts.publish,1);});
test('abandoned unsubmitted R2 object is cleaned after TTL',async()=>{const f=fixture();await f.app.create(f.id,`https://instagram.com/reel/${f.code}/`);await f.app.advance(f.id);f.age();await f.app.maintenance();assert.equal(await bucket.head(`temp-reels/${f.id}/source.mp4`),null);});
test('Meta API creates REELS with exact caption and requires returned numeric media ID',async()=>{const env={INSTAGRAM_USER_ID:'11111',INSTAGRAM_ACCESS_TOKEN:'never-show-token',INSTAGRAM_APP_SECRET:'never-show-secret'};const calls=[];const m=new MetaClient(env,'never-show-token',async(u,o)=>{calls.push({u,o});return Response.json({id:'12345678'});});await m.create('https://transport.example/video.mp4');assert.equal(JSON.parse(calls[0].o.body).caption,CAPTION);assert.equal(JSON.parse(calls[0].o.body).media_type,'REELS');assert.equal(new URL(calls[0].u).hostname,'graph.instagram.com');assert.ok(new URL(calls[0].u).pathname.startsWith('/v26.0/'));const bad=new MetaClient(env,'never-show-token',async()=>Response.json({success:true}));await assert.rejects(()=>bad.publish('12345678'));});
test('Meta errors redact credentials and URLs',async()=>{const env={INSTAGRAM_USER_ID:'11111',INSTAGRAM_ACCESS_TOKEN:'secret-token',INSTAGRAM_APP_SECRET:'secret-app'};const m=new MetaClient(env,'secret-token',async()=>Response.json({error:{message:'bad secret-token secret-app https://server.test/?access_token=secret-token'}},{status:400}));await assert.rejects(()=>m.create('https://transport.example/a'),e=>!e.message.includes('secret-token')&&!e.message.includes('secret-app')&&!e.message.includes('https://'));});
test('token exchange persists encrypted token and refreshes securely near expiry',async()=>{await db.prepare('DELETE FROM token_state').run();const f=fixture();let t=Date.now(),requests=0;const fetcher=async u=>{requests++;assert.equal(new URL(u).hostname,'graph.instagram.com');return Response.json({access_token:requests===1?'long-lived-test-token':'refreshed-test-token',expires_in:5184000});};assert.equal(await getAccessToken(f.env,fetcher,t),'long-lived-test-token');let row=await db.prepare('SELECT * FROM token_state').first();assert.ok(!JSON.stringify(row).includes('long-lived-test-token'));assert.equal(await getAccessToken(f.env,fetcher,t+1000),'long-lived-test-token');assert.equal(requests,1);assert.equal(await getAccessToken(f.env,fetcher,t+55*86400000),'refreshed-test-token');assert.equal(requests,2);});
test('already long-lived token is verified with official refresh after exchange rejection',async()=>{await db.prepare('DELETE FROM token_state').run();const f=fixture();const calls=[];const fetcher=async u=>{const url=new URL(u);calls.push(url.pathname);return calls.length===1?Response.json({error:{code:452}},{status:400}):Response.json({access_token:'existing-long-lived',expires_in:5184000});};assert.equal(await getAccessToken(f.env,fetcher,Date.now()),'existing-long-lived');assert.deepEqual(calls,['/access_token','/refresh_access_token']);const row=await db.prepare('SELECT * FROM token_state').first();assert.ok(!JSON.stringify(row).includes('existing-long-lived'));});
test('invalid initial token is rejected if both lifecycle endpoints fail',async()=>{await db.prepare('DELETE FROM token_state').run();const f=fixture();const fetcher=async()=>Response.json({error:{code:452}},{status:400});await assert.rejects(()=>getAccessToken(f.env,fetcher,Date.now()));assert.equal(await db.prepare('SELECT * FROM token_state').first(),null);});
test('transport exposes no UI, administration, or arbitrary upstream URLs',async()=>{for(const path of['/','/api/jobs','/video/http://internal/a','/video/bad/token/source.mp4'])assert.equal((await relay.fetch(new Request('https://relay.example'+path),{})).status,404);assert.equal((await relay.fetch(new Request('https://relay.example/video/'+crypto.randomUUID()+'/'+'a'.repeat(64)+'/source.mp4',{method:'POST'}),{})).status,404);});
