export function page(nonce){return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Reel Reposter</title><meta name="description" content="Your private Instagram Reel reposting utility."><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='18' fill='%23ff694f'/%3E%3Cpath d='M26 18v28l22-14z' fill='%230e1525'/%3E%3C/svg%3E">
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#0e1525;color:#f6f7fb;font:16px/1.55 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;min-height:100svh;display:grid;place-items:center;padding:28px}main{width:min(100%,470px)}.mark{width:48px;height:48px;background:#ff694f;border-radius:15px;display:grid;place-items:center;color:#101727;margin-bottom:24px}.mark svg{width:25px;height:25px}h1{font-size:clamp(2rem,7vw,2.7rem);letter-spacing:-.05em;line-height:1.2;margin:0 0 14px;font-weight:700}.connection{font-size:.94rem;color:#a9b4ca;min-height:28px;margin:0 0 34px}.connection.ok{color:#75deb4}label{display:block;margin-bottom:9px;color:#bac4d6;font-size:.875rem}input{width:100%;background:#172135;border:1px solid #344056;border-radius:12px;color:#fff;font:inherit;padding:17px 16px;outline:none}input::placeholder{color:#8b97af}input:focus{border-color:#ff8b72;box-shadow:0 0 0 3px #ff694f22}button{width:100%;border:0;background:#ff694f;color:#171b27;border-radius:12px;font:700 .94rem/1.5 system-ui;letter-spacing:.05em;padding:17px;margin-top:14px;cursor:pointer}button:hover{background:#ff826c}button:focus-visible{outline:3px solid #fff;outline-offset:4px}button:disabled{opacity:.5;cursor:wait}.caption{border-top:1px solid #2a3447;margin-top:31px;padding-top:22px}.caption span{font-size:.875rem;color:#92a0b7}.caption p{margin:6px 0 0;letter-spacing:.02em;font-weight:600}.result{margin-top:23px;min-height:54px;font-size:.94rem;color:#b9c5dc;overflow-wrap:anywhere}.result.error{color:#ffad9c}.result.success{color:#75deb4}.result a{color:inherit}.progress{height:3px;border-radius:3px;background:#29364e;margin-top:13px;overflow:hidden}.progress i{display:block;background:#ff826c;height:100%;width:40%;animation:move 1.5s infinite ease-in-out}@keyframes move{from{transform:translateX(-100%)}to{transform:translateX(350%)}}@media(prefers-reduced-motion:reduce){.progress i{animation:none;width:100%}}[hidden]{display:none!important}</style></head>
<body><main><div class="mark" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><rect x="3" y="3" width="18" height="18" rx="5" stroke="currentColor" stroke-width="1.8"/><path d="m10 8 6 4-6 4V8Z" fill="currentColor"/></svg></div><h1>Reel Reposter</h1><p class="connection" id="connection" role="status">Checking Instagram connection…</p><form id="form"><label for="url">Instagram Reel URL</label><input id="url" name="url" type="url" placeholder="Paste Instagram Reel URL" required autocomplete="off" spellcheck="false" maxlength="2048"><button id="post" type="submit" disabled>POST REEL</button></form><section class="caption"><span>Caption</span><p>FOLLOW FOR MORE!</p></section><div class="result" id="result" role="status" aria-live="polite"></div><div class="progress" id="progress" hidden aria-hidden="true"><i></i></div><button id="retry" hidden>RETRY</button></main>
<script nonce="${nonce}">
const $=id=>document.getElementById(id);let active=null,busy=false,connected=false;
const labels={downloading:'Downloading Reel…',preparing:'Preparing temporary video…',sending:'Sending to Instagram…',processing:'Instagram processing…',publishing:'Publishing…',published:'Published ✓',uncertain:'Checking publication outcome…',failed:'Failed'};
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data??{})});let d;try{d=await r.json()}catch{throw Error('The connection was interrupted. Reopen this page to resume your job.')}if(!r.ok)throw Error(d.error??'This request could not complete.');return d;}
function show(j){active=j;$('result').className='result'+(j.status==='published'?' success':j.status==='failed'||j.status==='uncertain'?' error':'');$('result').textContent=j.status==='failed'?(labels[j.failedStage]??j.failedStage??'Posting')+': '+j.error:labels[j.status]+(j.error?' '+j.error:'');$('retry').hidden=!j.retrySafe;}
async function follow(j){busy=true;$('post').disabled=true;$('url').disabled=true;$('progress').hidden=false;show(j);try{while(!['published','failed','uncertain'].includes(j.status)){await new Promise(r=>setTimeout(r,4000));j=await api('/api/jobs/'+j.id+'/advance');show(j);}if(j.status==='published'&&j.cleanupPending){j=await api('/api/jobs/'+j.id+'/advance');show(j);}}catch(e){$('result').className='result error';$('result').textContent=e.message+' Your saved job will resume when you reopen the page.';}finally{busy=false;$('progress').hidden=true;$('url').disabled=false;$('post').disabled=!connected;if(active&&['published','failed'].includes(active.status))localStorage.removeItem('reel-reposter-pending');}}
$('form').addEventListener('submit',async e=>{e.preventDefault();if(busy||!connected)return;busy=true;$('post').disabled=true;$('retry').hidden=true;const saved={id:crypto.randomUUID(),url:$('url').value};localStorage.setItem('reel-reposter-pending',JSON.stringify(saved));$('result').className='result';$('result').textContent='Starting…';try{const j=await api('/api/jobs',saved);await follow(j);}catch(e){$('result').className='result error';$('result').textContent=e.message;busy=false;$('post').disabled=!connected;}});
$('retry').addEventListener('click',async()=>{if(busy||!active)return;$('retry').hidden=true;try{await follow(await api('/api/jobs/'+active.id+'/retry'));}catch(e){$('result').textContent=e.message;}});
async function init(){try{await api('/api/connection');connected=true;$('connection').textContent='Instagram connected ✓';$('connection').classList.add('ok');$('post').disabled=false;const value=localStorage.getItem('reel-reposter-pending');if(value){let saved;try{saved=JSON.parse(value)}catch{localStorage.removeItem('reel-reposter-pending');return;}$('url').value=saved.url;await follow(await api('/api/jobs',saved));}}catch(e){$('connection').textContent='Instagram needs attention';$('result').className='result error';$('result').textContent=e.message;}}
init();
</script></body></html>`;}
