export function page(nonce){return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Reel Reposter</title><meta name="description" content="Your private Instagram Reel reposting utility."><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='18' fill='%23ff694f'/%3E%3Cpath d='M26 18v28l22-14z' fill='%230e1525'/%3E%3C/svg%3E">
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#0e1525;color:#f6f7fb;font:16px/1.55 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;min-height:100svh;display:grid;place-items:center;padding:28px}main{width:min(100%,470px)}.mark{width:48px;height:48px;background:#ff694f;border-radius:15px;display:grid;place-items:center;color:#101727;margin-bottom:24px}.mark svg{width:25px;height:25px}h1{font-size:clamp(2rem,7vw,2.7rem);letter-spacing:-.05em;line-height:1.2;margin:0 0 14px;font-weight:700}.connection{font-size:.94rem;color:#a9b4ca;min-height:28px;margin:0 0 34px}.connection.ok{color:#75deb4}label{display:block;margin-bottom:9px;color:#bac4d6;font-size:.875rem}textarea{width:100%;background:#172135;color:#fff;border:1px solid #344056;border-radius:10px;padding:12px;font:inherit;min-height:90px}.reel-row{margin-bottom:20px}.edit-caption{width:auto;padding:5px 10px;margin:6px 0;background:#29364e;color:#bac4d6;font-size:.75rem}.row-status{font-size:.85rem;color:#75deb4}input{width:100%;background:#172135;border:1px solid #344056;border-radius:12px;color:#fff;font:inherit;padding:17px 16px;outline:none}input::placeholder{color:#8b97af}input:focus{border-color:#ff8b72;box-shadow:0 0 0 3px #ff694f22}button{width:100%;border:0;background:#ff694f;color:#171b27;border-radius:12px;font:700 .94rem/1.5 system-ui;letter-spacing:.05em;padding:17px;margin-top:14px;cursor:pointer}button:hover{background:#ff826c}button:focus-visible{outline:3px solid #fff;outline-offset:4px}button:disabled{opacity:.5;cursor:wait}.caption{border-top:1px solid #2a3447;margin-top:31px;padding-top:22px}.caption span{font-size:.875rem;color:#92a0b7}.caption p{margin:6px 0 0;letter-spacing:.02em;font-weight:600}.result{margin-top:23px;min-height:54px;font-size:.94rem;color:#b9c5dc;overflow-wrap:anywhere}.result.error{color:#ffad9c}.result.success{color:#75deb4}.result a{color:inherit}.progress{height:3px;border-radius:3px;background:#29364e;margin-top:13px;overflow:hidden}.progress i{display:block;background:#ff826c;height:100%;width:40%;animation:move 1.5s infinite ease-in-out}@keyframes move{from{transform:translateX(-100%)}to{transform:translateX(350%)}}@media(prefers-reduced-motion:reduce){.progress i{animation:none;width:100%}}[hidden]{display:none!important}</style></head>
<body><main><div class="mark" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><rect x="3" y="3" width="18" height="18" rx="5" stroke="currentColor" stroke-width="1.8"/><path d="m10 8 6 4-6 4V8Z" fill="currentColor"/></svg></div><h1>Reel Reposter</h1><p class="connection" id="connection" role="status">Checking Instagram connection…</p><form id="form"><div id="rows"></div><button id="add" type="button" class="edit-caption">+ ADD REEL</button><button id="post" type="submit" disabled>POST REELS</button></form><p style="color:#92a0b7;font-size:.85rem">Up to 5 links, posted one by one. Keep this page open; reopening resumes your saved queue.</p><div class="result" id="result" role="status" aria-live="polite"></div><div class="progress" id="progress" hidden aria-hidden="true"><i></i></div><button id="retry" hidden>RETRY</button></main>
<script nonce="${nonce}">
const $=id=>document.getElementById(id);let busy=false,connected=false,queue=[];
const labels={downloading:'Downloading Reel…',preparing:'Preparing temporary video…',sending:'Sending to Instagram…',processing:'Instagram processing…',publishing:'Publishing…',published:'Published ✓',uncertain:'Check Instagram before retrying',failed:'Failed'};
function addRow(value={}){const i=$('rows').children.length;if(i>=5)return;const row=document.createElement('section');row.className='reel-row';row.innerHTML='<label>Reel '+(i+1)+'</label><input type="url" placeholder="Paste Instagram Reel URL" maxlength="2048" autocomplete="off"><div class="caption"><span>Caption</span><p>FOLLOW FOR MORE!</p><button class="edit-caption" type="button">EDIT CAPTION</button><textarea hidden maxlength="4400" aria-label="Caption for Reel '+(i+1)+'">FOLLOW FOR MORE!</textarea></div><div class="row-status" role="status"></div>';row.querySelector('input').value=value.url||'';row.querySelector('textarea').value=value.caption??'FOLLOW FOR MORE!';row.querySelector('.edit-caption').onclick=()=>{const t=row.querySelector('textarea');t.hidden=!t.hidden;row.querySelector('.caption p').hidden=!t.hidden;if(!t.hidden)t.focus();};$('rows').append(row);$('add').hidden=i===4;}
function lock(value){busy=value;document.querySelectorAll('input,textarea,button').forEach(e=>e.disabled=value);$('post').disabled=value||!connected;$('progress').hidden=!value;}
async function api(path,data={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(r.status===401){location.reload();throw Error('Unlock again to resume.');}if(!r.ok)throw Error(d.error||'Request failed.');return d;}
function save(){localStorage.setItem('reel-reposter-queue',JSON.stringify(queue));}
async function run(){lock(true);$('result').textContent='Posting queue…';$('retry').hidden=true;try{for(let i=0;i<queue.length;i++){const q=queue[i],row=$('rows').children[i],status=row.querySelector('.row-status');if(q.done){status.textContent='Published ✓';continue;}let j=await api('/api/jobs',q);while(true){status.textContent=labels[j.status]+(j.error?' '+j.error:'');if(j.status==='published'){if(j.cleanupPending){j=await api('/api/jobs/'+j.id+'/advance');if(j.cleanupPending)throw Error('Published; waiting for temporary-video cleanup.');}q.done=true;save();break;}if(j.status==='failed'||j.status==='uncertain'){q.jobId=j.id;q.retrySafe=j.retrySafe;save();$('retry').hidden=!j.retrySafe;throw Error('Queue stopped at Reel '+(i+1)+'. '+(j.error||labels[j.status]));}await new Promise(r=>setTimeout(r,4000));j=await api('/api/jobs/'+j.id+'/advance');}}localStorage.removeItem('reel-reposter-queue');$('result').textContent='All Reels published ✓';}catch(e){$('result').textContent=e.message+' Reopen this page to resume the saved queue.';}finally{lock(false);}}
$('add').onclick=()=>addRow();
$('form').onsubmit=e=>{e.preventDefault();if(busy||!connected)return;const entries=[...$('rows').children].map(row=>({url:row.querySelector('input').value.trim(),caption:row.querySelector('textarea').value})).filter(q=>q.url);if(!entries.length){$('result').textContent='Paste at least one Reel URL.';return;}if(entries.some(q=>[...q.caption].length>2200)){ $('result').textContent='Captions can contain at most 2,200 characters.';return;}queue=entries.map(q=>({...q,id:crypto.randomUUID()}));$('rows').replaceChildren();queue.forEach(addRow);save();run();};
$('retry').onclick=async()=>{const q=queue.find(q=>!q.done);if(!q?.retrySafe||busy)return;try{await api('/api/jobs/'+q.jobId+'/retry');await run();}catch(e){$('result').textContent=e.message;}};
async function init(){let saved;try{saved=JSON.parse(localStorage.getItem('reel-reposter-queue')||'null');}catch{}if(Array.isArray(saved)&&saved.length&&saved.length<=5){queue=saved;queue.forEach(addRow);}else for(let i=0;i<5;i++)addRow();try{await api('/api/connection');connected=true;$('connection').textContent='Instagram connected ✓';$('connection').classList.add('ok');$('post').disabled=false;if(queue.length)await run();}catch(e){$('connection').textContent='Instagram needs attention';$('result').textContent=e.message;}}
init();
</script></body></html>`;}
